### ISSUE TITLE
agent error 429

### ISSUE THREAD

**Issue by darkship** [meteorhacks/kadira#165]
Hi,

I'm trying to optimise my app in UAT and by the way I'm scaling it using cluster with multi-core support and multi-balancer for testing purpose but I keep getting <code>Kadira: agent error: 429</code>.

Is it <code>429 Too Many Requests</code> ? What can I do to solve it?

**Comment by arunoda** [comment]
This happens because you are using a lot of host and sending data to kadira.
So, this is an error blocked from our rate limiting system.

Currently, we allow 15 requests per minute. Mostly, limit is around 20-30
hosts.
Do you need to increase it?

**Comment by darkship** [comment]
That would be nice but I think it's useless. My app would certainly reach the limit again.

Could it be possible to filter out the error from the app log and display it in kadira's board since it actually is a response from kadira's server ?

**Comment by arunoda** [comment]
We don't have that kind of error reporting yet. Actually, we didn't think
about that.

It's pretty hard to deal with these kind of issues since we can't figure
out good and bad connections. So, reporting these issue also adds loads to
our servers. (Not in your case, but when we are hitting dos attacks)

How many hosts you will be having at max concurrently?

**Comment by darkship** [comment]
first server : 4 (CLUSTER_WORKERS_COUNT=3)
2nd server : 13 (CLUSTER_WORKERS_COUNT=12)

So if I'm right, it's 17.

**Comment by arunoda** [comment]
Okay. I'll try to increase this for you.
Send me your appId
